version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: datocms-client
    versions:
    - 3.2.2
    - 3.2.3
    - 3.3.0
    - 3.4.2
    - 3.4.3
    - 3.4.4
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: gatsby-link
    versions:
    - 2.10.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
